### ISSUE TITLE
Git Clone Error

### ISSUE THREAD

**Issue by trmcnealy** [xoofx/libclang#1]
D:\Github\xoofx>git clone https://github.com/xoofx/libclang.git
Cloning into 'libclang'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 55 (delta 14), reused 48 (delta 7), pack-reused 0
Unpacking objects: 100% (55/55), done.
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

D:\Github\xoofx>cd libclang

D:\Github\xoofx\libclang>git checkout -f HEAD
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly

Git Gui is showing some unstaged and staged changes...

**Comment by xoofx** [comment]
> `git-lfs filter-process: git-lfs: command not found`

This repository is using git lfs. You need to have it installed (either install it along git or follow [Installing Git Large File Storage](https://help.github.com/en/articles/installing-git-large-file-storage))

I will update the readme

**Comment by xoofx** [comment]
Readme is [updated](https://github.com/xoofx/libclang#0-make-sure-git-lfs-is-installed-on-your-machine)
